# 사이트 설정
title: 구름 속 질서를 설계하는 엔지니어
description: 클라우드 엔지니어 윤순상의 기술 블로그
author: 윤순상
url: https://yunsoonsang.github.io
baseurl: ""

# 블로그 설정
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Jekyll 설정
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed